# Generated by Django 5.2.12 on 2026-03-28 07:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookseries',
            options={'ordering': ['title'], 'verbose_name': 'Book Series', 'verbose_name_plural': 'Book Series'},
        ),
        migrations.AlterModelOptions(
            name='seriesvolume',
            options={'ordering': ['series', 'volume_number'], 'verbose_name': 'Series Volume', 'verbose_name_plural': 'Series Volumes'},
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seriesvolume',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
