# Generated by Django 5.2.12 on 2026-03-28 14:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_series_arc_type_lookup'),
        ('series', '0002_narrative_role_antagonist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesArc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('series_want', models.TextField(blank=True, default='', help_text='Was verfolgt die Hauptfigur über ALLE Bände hinweg?', verbose_name='Serien-Want')),
                ('series_need', models.TextField(blank=True, default='', help_text='Was braucht sie wirklich — wird erst im letzten Band klar.', verbose_name='Serien-Need')),
                ('series_false_belief', models.TextField(blank=True, default='', verbose_name='Überzeugung Serien-Beginn')),
                ('series_true_belief', models.TextField(blank=True, default='', verbose_name='Erkenntnis Serien-Ende')),
                ('overarching_conflict', models.TextField(blank=True, default='', help_text='Antagonist / Hindernis, das über alle Bände aktiv ist.', verbose_name='Übergreifender Konflikt')),
                ('series_theme_question', models.TextField(blank=True, default='', help_text='Die Frage, die die gesamte Serie stellt.', verbose_name='Serien-Themen-Frage')),
                ('total_volumes_planned', models.PositiveSmallIntegerField(default=3, verbose_name='Geplante Bände')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arc_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_arcs', to='core.seriesarctypelookup')),
                ('series', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arc', to='series.bookseries')),
            ],
            options={
                'verbose_name': 'Serien-Arc',
                'verbose_name_plural': 'Serien-Arcs',
                'db_table': 'wh_series_arcs',
            },
        ),
        migrations.CreateModel(
            name='SeriesVolumeRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arc_position', models.CharField(choices=[('opening', 'Eröffnung — Welt und Figuren einführen'), ('escalation', 'Eskalation — Einsätze erhöhen'), ('midpoint', 'Serien-Midpoint — alles dreht sich'), ('darkest', 'Dunkelster Band — alles scheint verloren'), ('climax_prep', 'Climax-Vorbereitung'), ('finale', 'Finale — Serien-Arc auflösen'), ('standalone', 'Eigenständig (Anthologie)')], default='escalation', max_length=20, verbose_name='Arc-Position im Serien-Bogen')),
                ('series_arc_contribution', models.TextField(blank=True, default='', help_text='Welchen Teil des Serien-Arcs trägt dieser Band?', verbose_name='Beitrag zum Serien-Arc')),
                ('promise_to_reader', models.TextField(blank=True, default='', help_text='Was verspricht dieses Buch für den nächsten Band?', verbose_name='Versprechen an den Leser')),
                ('promise_fulfilled_from', models.TextField(blank=True, default='', help_text='Welches Versprechen aus dem Vorgänger-Band wird hier eingelöst?', verbose_name='Eingelöstes Versprechen')),
                ('cliffhanger_type', models.CharField(choices=[('none', 'Kein Cliffhanger'), ('question', 'Offene Frage'), ('revelation', 'Enthüllung'), ('status_change', 'Figurenstatus verändert'), ('threat', 'Neue Bedrohung etabliert')], default='none', max_length=20)),
                ('cliffhanger_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('volume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='series.seriesvolume')),
            ],
            options={
                'verbose_name': 'Serien-Band-Rolle',
                'verbose_name_plural': 'Serien-Band-Rollen',
                'db_table': 'wh_series_volume_roles',
            },
        ),
        migrations.CreateModel(
            name='SeriesCharacterContinuity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('character_id', models.UUIDField(verbose_name='Figur (WeltenHub UUID)')),
                ('character_name', models.CharField(help_text='Gecacht — vermeidet API-Call bei jeder Anzeige', max_length=200, verbose_name='Figurenname (Cache)')),
                ('physical_state', models.TextField(blank=True, default='', verbose_name='Physischer Zustand')),
                ('emotional_state', models.TextField(blank=True, default='', verbose_name='Emotionaler Zustand')),
                ('arc_progress', models.TextField(blank=True, default='', verbose_name='Arc-Fortschritt')),
                ('knowledge_gained', models.JSONField(default=list, verbose_name='Neu erworbenes Wissen')),
                ('relationships_changed', models.JSONField(default=dict, verbose_name='Veränderte Beziehungen')),
                ('unresolved_threads', models.JSONField(default=list, verbose_name='Offene Fäden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_continuities', to='series.bookseries')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_continuities', to='series.seriesvolume', verbose_name='Am Ende von Band')),
            ],
            options={
                'verbose_name': 'Figur-Kontinuität',
                'verbose_name_plural': 'Figur-Kontinuitäten',
                'db_table': 'wh_series_character_continuities',
                'ordering': ['series', 'volume__volume_number', 'character_name'],
                'unique_together': {('series', 'volume', 'character_id')},
            },
        ),
    ]
