# Generated by Django 5.2.12 on 2026-03-28 07:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_narrative_role_antagonist'),
        ('core', '0001_lookups_drama'),
        ('projects', '0013_publishingprofile'),
        ('series', '0002_narrative_role_antagonist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorstylelookup',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Autor / Schreibstil (Legacy)', 'verbose_name_plural': 'Autoren / Schreibstile (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='bookproject',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Book Project', 'verbose_name_plural': 'Book Projects'},
        ),
        migrations.AlterModelOptions(
            name='chapterediting',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kapitel-Editing', 'verbose_name_plural': 'Kapitel-Editings'},
        ),
        migrations.AlterModelOptions(
            name='chapterreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kapitel-Review', 'verbose_name_plural': 'Kapitel-Reviews'},
        ),
        migrations.AlterModelOptions(
            name='lektoratissue',
            options={'ordering': ['session', 'node__order', '-severity'], 'verbose_name': 'Lektorats-Problem', 'verbose_name_plural': 'Lektorats-Probleme'},
        ),
        migrations.AlterModelOptions(
            name='lektoratsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lektorats-Session', 'verbose_name_plural': 'Lektorats-Sessions'},
        ),
        migrations.AlterModelOptions(
            name='outlinenode',
            options={'ordering': ['outline_version', 'order'], 'verbose_name': 'Outline Node', 'verbose_name_plural': 'Outline Nodes'},
        ),
        migrations.AlterModelOptions(
            name='outlineversion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Outline Version', 'verbose_name_plural': 'Outline Versions'},
        ),
        migrations.AlterField(
            model_name='audiencelookup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='authorstylelookup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='authorstylelookup',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='bookproject',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookproject',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='series.bookseries', verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='bookproject',
            name='writing_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='authors.writingstyle', verbose_name='Primärer Schreibstil'),
        ),
        migrations.AlterField(
            model_name='chapterediting',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chapterreview',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contenttypelookup',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contenttypelookup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contenttypelookup',
            name='planning_action_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contenttypelookup',
            name='planning_prompt_template',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='contenttypelookup',
            name='planning_system_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contenttypelookup',
            name='planning_user_template',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contenttypelookup',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contenttypelookup',
            name='workflow_hint',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='genrelookup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lektoratissue',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lektoratsession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manuscriptsnapshot',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='outlineframework',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='outlineframework',
            name='key',
            field=models.SlugField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='outlineframeworkbeat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='outlinenode',
            name='act',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='outlinenode',
            name='beat_phase',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='outlinenode',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='outlinenode',
            name='content_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outlinenode',
            name='emotional_arc',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='outlinenode',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='outlinenode',
            name='target_words',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outlinenode',
            name='word_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='outlineversion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='outlineversion',
            name='source',
            field=models.CharField(default='manual', max_length=80),
        ),
        migrations.AlterField(
            model_name='outlineversion',
            name='version_label',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='publishingprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ProjectGenrePromise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=True, help_text='Haupt-Genre-Versprechen (für LLM-Layer 10)')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre_promise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='core.genrepromiselookup', verbose_name='Genre-Versprechen')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_promises', to='projects.bookproject')),
            ],
            options={
                'verbose_name': 'Projekt-Genre-Versprechen',
                'verbose_name_plural': 'Projekt-Genre-Versprechen',
                'db_table': 'wh_project_genre_promises',
                'ordering': ['project', '-is_primary'],
                'unique_together': {('project', 'genre_promise')},
            },
        ),
    ]
