# Generated by Django 5.2.12 on 2026-03-28 07:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_narrative_role_antagonist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubplotArc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('story_label', models.CharField(choices=[('a_story', 'A-Story — Haupthandlung'), ('b_story', 'B-Story — Thematischer Spiegel'), ('c_story', 'C-Story — Weiterer Subplot')], db_index=True, default='b_story', max_length=10)),
                ('title', models.CharField(max_length=200, verbose_name='Subplot-Bezeichnung')),
                ('carried_by_character_id', models.UUIDField(blank=True, null=True, verbose_name='Träger-Figur (WeltenHub UUID)')),
                ('carried_by_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Träger-Figur (Cache)')),
                ('thematic_mirror', models.TextField(blank=True, default='', help_text='Wie spiegelt dieser Subplot das Thema der A-Story?', verbose_name='Thematischer Spiegel')),
                ('embodies_need', models.BooleanField(default=True, verbose_name='Verkörpert das Need')),
                ('begins_at_percent', models.PositiveSmallIntegerField(default=37, help_text='Empfehlung Drei-Akte/Save-the-Cat: 37%.', verbose_name='Beginn (%)')),
                ('ends_at_percent', models.PositiveSmallIntegerField(default=95, verbose_name='Ende (%)')),
                ('intersection_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('begins_at_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subplot_begins', to='projects.outlinenode', verbose_name='Beginnt in Kapitel/Szene')),
                ('ends_at_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subplot_ends', to='projects.outlinenode', verbose_name='Endet in Kapitel/Szene')),
                ('intersection_nodes', models.ManyToManyField(blank=True, help_text='Kapitel/Szenen, in denen dieser Subplot die A-Story kreuzt.', related_name='subplot_intersections', to='projects.outlinenode')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subplot_arcs', to='projects.bookproject')),
            ],
            options={
                'verbose_name': 'Subplot-Arc',
                'verbose_name_plural': 'Subplot-Arcs',
                'db_table': 'wh_subplot_arcs',
                'ordering': ['project', 'story_label'],
            },
        ),
    ]
