# Generated by Django 5.2.12 on 2026-03-28 14:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_subplot_arc_genre_promise'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnalysisSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dead_scene_count', models.PositiveSmallIntegerField(default=0, help_text='Anzahl Nodes mit emotion_start == emotion_end (beide befüllt)')),
                ('dead_scene_node_ids', models.JSONField(default=list, help_text='UUIDs der betroffenen OutlineNodes')),
                ('character_screen_time', models.JSONField(default=dict, help_text='{character_uuid: {chapters: int, percent: float, last_seen_order: int, role: str}}')),
                ('chapter_word_counts', models.JSONField(default=list, help_text='[{order: int, word_count: int, title: str}]')),
                ('pacing_variance', models.FloatField(blank=True, help_text='Standardabweichung der Kapitel-Wortanzahlen', null=True)),
                ('pacing_issues', models.JSONField(default=list, help_text='[{type: str, severity: str, description: str, chapter_orders: []}]')),
                ('dialogue_ratios', models.JSONField(default=dict, help_text='{chapter_order: float} — geschätzter Dialog-Anteil 0.0–1.0')),
                ('voice_drift_checked', models.BooleanField(default=False)),
                ('voice_drift_detected', models.BooleanField(default=False)),
                ('voice_drift_chapters', models.JSONField(default=list, help_text='[{order: int, reason: str}]')),
                ('chapters_analyzed', models.PositiveSmallIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('triggered_by', models.CharField(choices=[('manual', 'Manuell ausgelöst'), ('lektorat', 'Nach Lektorat'), ('save', 'Nach Kapitel-Speichern')], default='manual', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_snapshots', to='projects.bookproject')),
            ],
            options={
                'verbose_name': 'Text-Analyse-Snapshot',
                'verbose_name_plural': 'Text-Analyse-Snapshots',
                'db_table': 'wh_text_analysis_snapshots',
                'ordering': ['-computed_at'],
                'get_latest_by': 'computed_at',
            },
        ),
    ]
