# Generated by Django 5.2.12 on 2026-03-28 14:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_text_analysis_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaReaderSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('anonymization', models.CharField(choices=[('open', 'Offen — alles sichtbar'), ('anon_meta', 'Text only — keine Metadaten'), ('anon_full', 'Vollständig anonym')], default='anon_meta', max_length=20)),
                ('feedback_focus', models.CharField(choices=[('general', 'Allgemein'), ('pacing', 'Pacing & Tempo'), ('character', 'Figuren-Sympathie'), ('clarity', 'Verständlichkeit'), ('tension', 'Spannungsverlauf'), ('ending', 'Schluss / Auflösung')], default='general', max_length=20)),
                ('reader_name', models.CharField(blank=True, default='', max_length=200)),
                ('reader_note', models.TextField(blank=True, default='')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('manuscript_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beta_sessions', to='projects.manuscriptsnapshot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beta_sessions', to='projects.bookproject')),
            ],
            options={
                'verbose_name': 'Beta-Leser-Session',
                'verbose_name_plural': 'Beta-Leser-Sessions',
                'db_table': 'wh_beta_reader_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BetaReaderFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('confusion', 'Unklarheit / Verwirrung'), ('boredom', 'Langeweile / Tempo zu langsam'), ('tension_drop', 'Spannungsabfall'), ('highlight', 'Besonders gut'), ('character_ok', 'Figur sympathisch'), ('char_problem', 'Figur-Problem'), ('general', 'Allgemeines Feedback')], default='general', max_length=20)),
                ('text', models.TextField(verbose_name='Feedback-Text')),
                ('text_reference', models.TextField(blank=True, default='')),
                ('chapter_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_addressed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beta_feedbacks', to='projects.outlinenode')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='projects.betareadersession')),
            ],
            options={
                'verbose_name': 'Beta-Reader-Feedback',
                'verbose_name_plural': 'Beta-Reader-Feedbacks',
                'db_table': 'wh_beta_reader_feedbacks',
                'ordering': ['session', 'chapter_order', 'feedback_type'],
            },
        ),
        migrations.CreateModel(
            name='ComparableTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Buchtitel')),
                ('author', models.CharField(max_length=200, verbose_name='Autor')),
                ('publisher', models.CharField(blank=True, default='', max_length=200)),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, help_text='Für Validierung: Comps sollten < 5 Jahre alt sein.', null=True, verbose_name='Erscheinungsjahr')),
                ('relation_type', models.CharField(choices=[('similar_theme', 'Ähnliches Thema'), ('similar_tone', 'Ähnlicher Ton'), ('similar_structure', 'Ähnliche Struktur'), ('same_audience', 'Gleiche Zielgruppe'), ('same_subgenre', 'Gleiches Subgenre'), ('contrast', "Kontrast — 'wie X, aber Y'")], default='similar_theme', max_length=20)),
                ('similarity_note', models.TextField(blank=True, default='', verbose_name='Worin ähnlich')),
                ('difference_note', models.TextField(blank=True, default='', verbose_name='Worin anders')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparable_titles', to='projects.bookproject')),
            ],
            options={
                'verbose_name': 'Comparable Title',
                'verbose_name_plural': 'Comparable Titles',
                'db_table': 'wh_comparable_titles',
                'ordering': ['project', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='GenreConventionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conventions', models.JSONField(default=list, help_text='Liste von Konventions-Checks (check_type: turning_point_exists, b_story_exists, happy_end_required, fair_play)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre_lookup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='convention_profile', to='projects.genrelookup')),
            ],
            options={
                'verbose_name': 'Genre-Konventions-Profil',
                'verbose_name_plural': 'Genre-Konventions-Profile',
                'db_table': 'wh_genre_convention_profiles',
            },
        ),
        migrations.CreateModel(
            name='PitchDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pitch_type', models.CharField(choices=[('logline', 'Logline — 1 Satz'), ('one_pager', 'One-Pager — EN'), ('expose_de', 'Exposé — DE Verlagsstandard'), ('synopsis', 'Synopsis — vollständige Handlung'), ('query', 'Query Letter — US/UK')], db_index=True, max_length=20)),
                ('content', models.TextField(verbose_name='Inhalt')),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('ai_agent', models.CharField(blank=True, default='', max_length=100)),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text='Aktive Version dieses Typs (nur eine gleichzeitig).')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_documents', to='projects.bookproject')),
            ],
            options={
                'verbose_name': 'Pitch-Dokument',
                'verbose_name_plural': 'Pitch-Dokumente',
                'db_table': 'wh_pitch_documents',
                'ordering': ['project', 'pitch_type', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ResearchNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('fact', 'Fakt — verifiziert'), ('question', 'Offene Frage'), ('rule', 'Regel / Gesetz / Technologie'), ('atmosphere', 'Atmosphäre / Detail'), ('quote', 'Zitat')], default='fact', max_length=20)),
                ('title', models.CharField(max_length=300, verbose_name='Bezeichnung')),
                ('content', models.TextField(verbose_name='Inhalt')),
                ('source', models.CharField(blank=True, default='', help_text='URL, Buchtitel, Experteninterview', max_length=500)),
                ('is_verified', models.BooleanField(default=False, help_text='Nur verifizierte Notizen werden in LLM-Prompts injiziert.')),
                ('is_open_question', models.BooleanField(default=False, help_text='Noch unbeantwortet — wird im Health-Score gezählt.')),
                ('tags', models.JSONField(default=list)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_notes', to='projects.bookproject')),
                ('relevant_nodes', models.ManyToManyField(blank=True, help_text='Welche Kapitel/Szenen brauchen diese Notiz?', related_name='research_notes', to='projects.outlinenode')),
            ],
            options={
                'verbose_name': 'Recherche-Notiz',
                'verbose_name_plural': 'Recherche-Notizen',
                'db_table': 'wh_research_notes',
                'ordering': ['project', '-is_verified', 'note_type', 'sort_order'],
            },
        ),
    ]
