# Generated by Django 5.2.12 on 2026-03-28 14:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_comparable_title_pitch_research_beta'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlineSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('act', models.CharField(blank=True, default='', help_text="z.B. 'act_1', 'act_2a', 'act_3'", max_length=20, verbose_name='Akt-Zugehörigkeit')),
                ('title', models.CharField(max_length=200)),
                ('goal', models.TextField(help_text='Was versucht die Figur in dieser Sequenz zu erreichen?', verbose_name='Sequenz-Ziel')),
                ('start_state', models.TextField(blank=True, default='', verbose_name='Ausgangslage')),
                ('end_state', models.TextField(blank=True, default='', help_text='Positiv (Ziel erreicht) oder negativ (Komplikation)?', verbose_name='Endzustand')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('outline_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='projects.outlineversion')),
            ],
            options={
                'verbose_name': 'Sequenz',
                'verbose_name_plural': 'Sequenzen',
                'db_table': 'wh_outline_sequences',
                'ordering': ['outline_version', 'sort_order'],
            },
        ),
        migrations.AddField(
            model_name='outlinenode',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='projects.outlinesequence', verbose_name='Sequenz-Zugehörigkeit'),
        ),
    ]
