# Generated by Django 5.2.12 on 2026-03-28 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_outline_sequence_timeline_foreshadowing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeshadowingTypeLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Foreshadowing-Typ',
                'verbose_name_plural': 'Foreshadowing-Typen',
                'db_table': 'wh_foreshadowing_type_lookup',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='NarrativeModelLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Erzähl-Zeitmodell',
                'verbose_name_plural': 'Erzähl-Zeitmodelle',
                'db_table': 'wh_narrative_model_lookup',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ForeshadowingEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="Kurzer Name: 'Die Narbe an seiner Hand'", max_length=200, verbose_name='Bezeichner')),
                ('setup_description', models.TextField(help_text='Was wird eingeführt? Wie? In welchem Kontext?', verbose_name='Setup')),
                ('payoff_description', models.TextField(blank=True, default='', help_text='Wie wird es aufgelöst?', verbose_name='Payoff')),
                ('thematic_meaning', models.TextField(blank=True, default='', verbose_name='Thematische Bedeutung')),
                ('status', models.CharField(choices=[('open', 'Geplant (noch nicht eingebaut)'), ('planted', 'Eingebaut (wartet auf Auflösung)'), ('resolved', 'Aufgelöst'), ('abandoned', 'Aufgegeben')], default='open', max_length=20)),
                ('abandonment_reason', models.TextField(blank=True, default='', verbose_name='Grund für Aufgabe')),
                ('is_planted', models.BooleanField(default=False, help_text="Shortcut-Flag: True wenn status='planted' oder 'resolved'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('introduced_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreshadowing_setups', to='projects.outlinenode', verbose_name='Eingeführt in')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreshadowing_entries', to='projects.bookproject')),
                ('resolved_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreshadowing_payoffs', to='projects.outlinenode', verbose_name='Aufgelöst in')),
                ('setup_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreshadowing_setups_alt', to='projects.outlinenode', verbose_name='Setup-Node (Fair-Play-Check)')),
                ('foreshadow_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.foreshadowingtypelookup')),
            ],
            options={
                'verbose_name': 'Foreshadowing-Eintrag',
                'verbose_name_plural': 'Foreshadowing-Einträge',
                'db_table': 'wh_foreshadowing_entries',
                'ordering': ['project', 'status', 'label'],
            },
        ),
        migrations.CreateModel(
            name='MasterTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('story_time_span', models.CharField(blank=True, default='', help_text="z.B. '3 Wochen', 'Sommer 1989', '200 Jahre Zukunft'", max_length=200, verbose_name='Story-Zeitraum')),
                ('story_start_date', models.CharField(blank=True, default='', help_text='Narrativer Startpunkt (kein DateField — kann fiktiv sein).', max_length=100, verbose_name='Story-Startpunkt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_timeline', to='projects.bookproject')),
                ('narrative_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timelines', to='projects.narrativemodellookup', verbose_name='Erzähl-Zeitmodell')),
            ],
            options={
                'verbose_name': 'Master-Chronologie',
                'verbose_name_plural': 'Master-Chronologien',
                'db_table': 'wh_master_timelines',
            },
        ),
        migrations.CreateModel(
            name='PlannedFlashback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_summary', models.TextField(verbose_name='Inhalt der Rückblende')),
                ('dramatic_purpose', models.TextField(help_text='Warum jetzt? Was trägt dieser Flashback zur Szene/Arc bei?', verbose_name='Dramaturgischer Zweck')),
                ('technique', models.CharField(choices=[('hard_cut', 'Hard Cut (abrupter Wechsel)'), ('trigger', 'Trigger (Sinneseindruck)'), ('chapter_break', 'Kapitelwechsel (ganzes Kapitel als Rückblende)')], default='trigger', max_length=20)),
                ('return_technique', models.TextField(blank=True, default='', verbose_name='Rückkehr-Technik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_flashbacks', to='projects.bookproject')),
                ('trigger_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashback_triggers', to='projects.outlinenode', verbose_name='Ausgelöst in Szene')),
            ],
            options={
                'verbose_name': 'Geplante Rückblende',
                'verbose_name_plural': 'Geplante Rückblenden',
                'db_table': 'wh_planned_flashbacks',
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('pre_story', 'Pre-Story (Vorgeschichte)'), ('story', 'Story (Handlung)'), ('post_story', 'Post-Story (Implied Future)')], default='story', max_length=20)),
                ('story_date', models.CharField(blank=True, default='', help_text="Narrativer Zeitpunkt z.B. 'Tag 3, 14:00'", max_length=100)),
                ('event_description', models.TextField(verbose_name='Ereignis-Beschreibung')),
                ('characters_involved', models.JSONField(default=list, help_text='WeltenHub-UUIDs der beteiligten Figuren')),
                ('order', models.PositiveIntegerField(default=0)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_entries', to='projects.outlinenode', verbose_name='Verknüpfte Szene/Kapitel')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='projects.mastertimeline')),
            ],
            options={
                'verbose_name': 'Chronologie-Eintrag',
                'verbose_name_plural': 'Chronologie-Einträge',
                'db_table': 'wh_timeline_entries',
                'ordering': ['timeline', 'order'],
            },
        ),
    ]
