# Generated by Django 5.2.12 on 2026-03-28 14:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_series_arc_type_lookup'),
        ('projects', '0019_timeline_foreshadowing_flashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlinenode',
            name='emotion_end',
            field=models.CharField(blank=True, default='', help_text="Dominante Emotion am Szenen-Ende (z.B. 'Verzweiflung')", max_length=100, verbose_name='Emotion Ende'),
        ),
        migrations.AddField(
            model_name='outlinenode',
            name='emotion_start',
            field=models.CharField(blank=True, default='', help_text="Dominante Emotion zu Szenen-Beginn (z.B. 'Hoffnung')", max_length=100, verbose_name='Emotion Beginn'),
        ),
        migrations.AddField(
            model_name='outlinenode',
            name='outcome',
            field=models.CharField(blank=True, choices=[('yes', 'Yes (Ziel erreicht)'), ('no', 'No (Ziel verfehlt)'), ('yes_but', 'Yes, but (mit Komplikation)'), ('no_and', 'No, and (Lage verschlechtert)')], default='', max_length=10, verbose_name='Szenen-Outcome'),
        ),
        migrations.AddField(
            model_name='outlinenode',
            name='tension_numeric',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Subjektiver Spannungswert 1–10 für die Spannungskurve', null=True, verbose_name='Spannungswert (1–10)'),
        ),
        migrations.CreateModel(
            name='ProjectTurningPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', help_text='Leer = Typ-Label verwenden', max_length=200, verbose_name='Bezeichnung (Override)')),
                ('position_percent', models.PositiveSmallIntegerField(default=0, help_text='0–100, relativer Buchfortschritt', verbose_name='Position (%)')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turning_point_markers', to='projects.outlinenode', verbose_name='Verknüpfte Szene')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turning_points', to='projects.bookproject')),
                ('turning_point_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_turning_points', to='core.turningpointtypelookup')),
            ],
            options={
                'verbose_name': 'Wendepunkt',
                'verbose_name_plural': 'Wendepunkte',
                'db_table': 'wh_project_turning_points',
                'ordering': ['project', 'position_percent'],
            },
        ),
    ]
