# Generated by Django 5.2.12 on 2026-03-28 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_drama_dashboard_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectturningpoint',
            name='mirrors_node',
            field=models.ForeignKey(blank=True, help_text='Nur für closing_image: die OutlineNode des Opening Image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mirrored_by_turning_points', to='projects.outlinenode', verbose_name='Gespiegelte Szene'),
        ),
    ]
