# Generated by Django 5.2.12 on 2026-03-28 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_adr158_dialogue_scene_genre_promise'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogueScene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker_a_character_id', models.UUIDField(blank=True, null=True, verbose_name='Figur A (WeltenHub UUID)')),
                ('speaker_a_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Figur A (Cache)')),
                ('speaker_b_character_id', models.UUIDField(blank=True, null=True, verbose_name='Figur B (WeltenHub UUID)')),
                ('speaker_b_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Figur B (Cache)')),
                ('goal_a', models.TextField(blank=True, default='', help_text='Was will Figur A durch dieses Gespräch erreichen?', verbose_name='Ziel Figur A im Dialog')),
                ('goal_b', models.TextField(blank=True, default='', verbose_name='Ziel Figur B im Dialog')),
                ('subtext_a', models.TextField(blank=True, default='', help_text='Was meint Figur A wirklich — darf es aber nicht sagen?', verbose_name='Subtext Figur A')),
                ('subtext_b', models.TextField(blank=True, default='', verbose_name='Subtext Figur B')),
                ('info_asymmetry', models.TextField(blank=True, default='', help_text='Was weiß eine Figur, was die andere nicht weiß?', verbose_name='Informations-Asymmetrie')),
                ('dialogue_outcome', models.CharField(choices=[('status_quo', 'Status Quo — nichts ändert sich (Ausnahme!)'), ('info_shift', 'Info-Shift — Wissensstand verändert sich'), ('power_shift', 'Power-Shift — Machtverhältnis kippt'), ('relationship', 'Beziehungs-Shift — Nähe/Distanz verändert'), ('revelation', 'Enthüllung — etwas kommt ans Licht'), ('decision', 'Entscheidungs-Katalysator')], default='info_shift', max_length=20, verbose_name='Dialog-Outcome')),
                ('outcome_description', models.TextField(blank=True, default='', help_text='Was ändert sich konkret durch diesen Dialog?', verbose_name='Outcome-Beschreibung')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_scenes', to='projects.outlinenode', verbose_name='Szene')),
            ],
            options={
                'verbose_name': 'Dialog-Subtext',
                'verbose_name_plural': 'Dialog-Subtexte',
                'db_table': 'wh_dialogue_scenes',
                'ordering': ['node', 'sort_order'],
            },
        ),
    ]
