# Generated by Django 5.2.12 on 2026-04-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_adr158_dialogue_scene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookproject',
            name='content_type',
            field=models.CharField(choices=[('novel', 'Roman'), ('nonfiction', 'Sachbuch'), ('short_story', 'Kurzgeschichte'), ('screenplay', 'Drehbuch'), ('essay', 'Essay'), ('academic', 'Akademische Arbeit (Monographie, Dissertation)'), ('scientific', 'Wissenschaftliches Paper (IMRaD)')], default='novel', max_length=30),
        ),
    ]
