# Generated by Django 5.2.6 on 2026-04-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_peer_review_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlinenode',
            name='emotional_arc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
