# Generated by Django 5.2.6 on 2026-04-16 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_alter_outlinenode_emotional_arc_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='genrelookup',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Leer = für alle Inhaltstypen verfügbar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genres', to='projects.contenttypelookup', verbose_name='Inhaltstyp'),
        ),
    ]
