# Generated by Django 5.2.6 on 2026-04-16 15:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_genre_content_type_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('authors_json', models.JSONField(blank=True, default=list)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, default='', max_length=200)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('abstract', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(choices=[('journal', 'Journal Article'), ('book', 'Buch'), ('conference', 'Konferenz'), ('web', 'Webquelle'), ('report', 'Report / White Paper'), ('thesis', 'Dissertation / Thesis')], default='journal', max_length=30)),
                ('added_via', models.CharField(choices=[('search', 'KI-Literaturrecherche'), ('doi', 'DOI-Lookup'), ('isbn', 'ISBN-Lookup'), ('bibtex', 'BibTeX-Import'), ('manual', 'Manuell')], default='search', max_length=20)),
                ('journal', models.CharField(blank=True, default='', max_length=300)),
                ('volume', models.CharField(blank=True, default='', max_length=50)),
                ('issue', models.CharField(blank=True, default='', max_length=50)),
                ('pages', models.CharField(blank=True, default='', max_length=50)),
                ('publisher', models.CharField(blank=True, default='', max_length=200)),
                ('bibtex', models.TextField(blank=True, default='')),
                ('relevance_note', models.TextField(blank=True, default='')),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citations', to='projects.outlinenode', verbose_name='Kapitel-Zuordnung')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='projects.bookproject')),
            ],
            options={
                'verbose_name': 'Projekt-Quelle',
                'verbose_name_plural': 'Projekt-Quellen',
                'db_table': 'wh_project_citations',
                'ordering': ['project', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('doi', ''), _negated=True), fields=('project', 'doi'), name='unique_project_doi')],
            },
        ),
    ]
