# Generated by Django 5.2.6 on 2026-04-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_add_project_citation'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlinenode',
            name='research_queries',
            field=models.JSONField(blank=True, default=list, help_text='KI-generierte Suchbegriffe für Literaturrecherche', verbose_name='Recherchefragen'),
        ),
    ]
