# Generated by Django 5.2.6 on 2026-04-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_add_research_queries_to_outlinenode'),
    ]

    operations = [
        migrations.AddField(
            model_name='lektoratissue',
            name='fix_text',
            field=models.TextField(blank=True, help_text='KI-generierter Korrekturvorschlag'),
        ),
        migrations.AddField(
            model_name='lektoratissue',
            name='quote',
            field=models.TextField(blank=True, help_text='Betroffene Textstelle (Zitat aus dem Kapitel)'),
        ),
    ]
