# Generated by Django 5.2.6 on 2026-04-18 07:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_lektorat_issue_quote_fixtext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Verlagsname')),
                ('imprint', models.CharField(blank=True, max_length=300, verbose_name='Imprint')),
                ('logo_url', models.URLField(blank=True, verbose_name='Logo-URL')),
                ('default_copyright_holder', models.CharField(blank=True, max_length=300)),
                ('default_language', models.CharField(default='de', max_length=10)),
                ('default_bisac_category', models.CharField(blank=True, max_length=200)),
                ('default_age_rating', models.CharField(blank=True, default='0', max_length=30)),
                ('website', models.URLField(blank=True)),
                ('is_default', models.BooleanField(default=True, help_text='Wird automatisch bei neuen Projekten als Vorlage verwendet.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verlagsprofil',
                'verbose_name_plural': 'Verlagsprofile',
                'db_table': 'wh_publisher_profiles',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
