# Generated by Django 5.2.6 on 2026-04-18 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_publisher_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('autor', 'Autor'), ('lektor', 'Lektor'), ('verleger', 'Verleger')], default='autor', max_length=20, verbose_name='Geschrieben als')),
                ('content', models.TextField(verbose_name='Notiz')),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_notes', to='projects.outlinenode')),
            ],
            options={
                'verbose_name': 'Kapitel-Notiz',
                'verbose_name_plural': 'Kapitel-Notizen',
                'db_table': 'wh_chapter_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhaseChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('concept', 'Konzept & Planung'), ('research', 'Recherche'), ('writing', 'Schreiben'), ('review', 'Lektorat & Review'), ('production', 'Publikation & Export')], max_length=30, verbose_name='Phase')),
                ('label', models.CharField(max_length=300, verbose_name='Checkpunkt')),
                ('is_checked', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='projects.bookproject')),
            ],
            options={
                'verbose_name': 'Phasen-Checkpunkt',
                'verbose_name_plural': 'Phasen-Checkpunkte',
                'db_table': 'wh_phase_checklist_items',
                'ordering': ['phase', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Meilenstein')),
                ('phase', models.CharField(blank=True, choices=[('concept', 'Konzept & Planung'), ('research', 'Recherche'), ('writing', 'Schreiben'), ('review', 'Lektorat & Review'), ('production', 'Publikation & Export')], default='', max_length=30, verbose_name='Phase')),
                ('due_date', models.DateField(verbose_name='Fälligkeitsdatum')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.bookproject')),
            ],
            options={
                'verbose_name': 'Meilenstein',
                'verbose_name_plural': 'Meilensteine',
                'db_table': 'wh_project_milestones',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Template-Name')),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('novel', 'Roman'), ('nonfiction', 'Sachbuch'), ('short_story', 'Kurzgeschichte'), ('screenplay', 'Drehbuch'), ('essay', 'Essay'), ('academic', 'Akademische Arbeit (Monographie, Dissertation)'), ('scientific', 'Wissenschaftliches Paper (IMRaD)')], default='novel', max_length=30)),
                ('framework_key', models.CharField(blank=True, default='three_act', max_length=100, verbose_name='Outline-Framework')),
                ('default_target_words', models.PositiveIntegerField(default=60000, verbose_name='Ziel-Wortzahl')),
                ('default_genre', models.CharField(blank=True, max_length=100)),
                ('default_audience', models.CharField(blank=True, max_length=200)),
                ('chapter_count_hint', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kapitelanzahl (Richtwert)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System-Templates können nicht gelöscht werden.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, help_text='NULL = globales Template für alle User.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projekt-Vorlage',
                'verbose_name_plural': 'Projekt-Vorlagen',
                'db_table': 'wh_project_templates',
                'ordering': ['content_type', 'name'],
            },
        ),
    ]
