# Generated by Django 5.2.12 on 2026-03-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_writingstyle_style_lab_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingstyle',
            name='description',
            field=models.TextField(blank=True, help_text='Kurzbeschreibung des Stils'),
        ),
        migrations.AlterField(
            model_name='writingstyle',
            name='do_list',
            field=models.JSONField(default=list, help_text='Erlaubte/empfohlene Stilmittel (Style Lab DO-Liste)'),
        ),
        migrations.AlterField(
            model_name='writingstyle',
            name='dont_list',
            field=models.JSONField(default=list, help_text='Verbotene Stilmittel (Style Lab DONT-Liste)'),
        ),
        migrations.AlterField(
            model_name='writingstyle',
            name='name',
            field=models.CharField(help_text="z.B. 'Thriller-Stil', 'Romantisch', 'Sachlich'", max_length=200),
        ),
        migrations.AlterField(
            model_name='writingstyle',
            name='signature_moves',
            field=models.JSONField(default=list, help_text='Charakteristische Stilmittel dieses Autors'),
        ),
        migrations.AlterField(
            model_name='writingstyle',
            name='source_text',
            field=models.TextField(blank=True, help_text='Originaltext der hochgeladen und analysiert wurde'),
        ),
        migrations.AlterField(
            model_name='writingstyle',
            name='style_profile',
            field=models.TextField(blank=True, help_text='LLM-generiertes Stil-Profil'),
        ),
        migrations.AlterField(
            model_name='writingstyle',
            name='style_prompt',
            field=models.TextField(blank=True, help_text='Kondensierter Prompt-Baustein für LLM-Generierung'),
        ),
        migrations.AlterField(
            model_name='writingstyle',
            name='taboo_list',
            field=models.JSONField(default=list, help_text='Tabu-Wörter (niemals verwenden)'),
        ),
    ]
