# Generated by Django 5.2.6 on 2026-04-16 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_narrative_role_antagonist'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('name_short', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Genre-Profil',
                'verbose_name_plural': 'Genre-Profile',
                'db_table': 'wh_genre_profiles',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='writingstylesample',
            name='situation',
            field=models.CharField(choices=[('action', 'Actionszene'), ('dialogue', 'Dialog'), ('description', 'Ortsbeschreibung'), ('emotion', 'Emotionale Szene'), ('intro', 'Kapiteleinstieg'), ('outro', 'Kapitelende / Cliffhanger'), ('inner', 'Innerer Monolog'), ('exposition', 'Exposition')], help_text='Legacy-Feld, wird durch situation_type ersetzt', max_length=30),
        ),
        migrations.AddField(
            model_name='writingstyle',
            name='genre_profile',
            field=models.ForeignKey(blank=True, help_text='Genre bestimmt die verfuegbaren Situationstypen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writing_styles', to='authors.genreprofile'),
        ),
        migrations.CreateModel(
            name='SituationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('llm_prompt_hint', models.TextField(blank=True, help_text='Zusaetzliche Analysekriterien fuer LLM-Prompts')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('genre_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_types', to='authors.genreprofile')),
            ],
            options={
                'verbose_name': 'Situationstyp',
                'verbose_name_plural': 'Situationstypen',
                'db_table': 'wh_situation_types',
                'ordering': ['sort_order'],
                'unique_together': {('genre_profile', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='writingstylesample',
            name='situation_type',
            field=models.ForeignKey(blank=True, help_text='Genre-spezifischer Situationstyp (ersetzt situation CharField)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='authors.situationtype'),
        ),
    ]
