# Generated by Django 5.2.6 on 2026-04-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_populate_genre_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingstyle',
            name='citation_style',
            field=models.CharField(blank=True, choices=[('apa', 'APA 7th'), ('ieee', 'IEEE'), ('acm', 'ACM'), ('harvard', 'Harvard'), ('chicago', 'Chicago'), ('din_iso', 'DIN ISO 690'), ('custom', 'Benutzerdefiniert')], help_text='Zitationsstil (APA, IEEE, ACM, ...)', max_length=20),
        ),
        migrations.AddField(
            model_name='writingstyle',
            name='domain',
            field=models.CharField(blank=True, help_text='Fachgebiet: Wirtschaftsinformatik, KI, BWL, ...', max_length=200),
        ),
        migrations.AddField(
            model_name='writingstyle',
            name='formality_level',
            field=models.CharField(blank=True, choices=[('high', 'Hoch-akademisch'), ('semi', 'Semi-formal'), ('popular', 'Populaerwissenschaftlich')], help_text='Formalitaetsgrad des Stils', max_length=20),
        ),
        migrations.AddField(
            model_name='writingstyle',
            name='language',
            field=models.CharField(blank=True, help_text='Sprache: de, en, de-en (Mixed)', max_length=10),
        ),
        migrations.AddField(
            model_name='writingstyle',
            name='publication_format',
            field=models.CharField(blank=True, help_text='Typisches Format: Conference Paper, Journal, Dissertation, ...', max_length=200),
        ),
        migrations.AddField(
            model_name='writingstyle',
            name='target_audience',
            field=models.CharField(blank=True, help_text='Zielgruppe: Fachpublikum, Studenten, Management, ...', max_length=120),
        ),
    ]
