# Generated by Django 5.2.6 on 2026-04-09 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0025_alter_outlinenode_emotional_arc_to_textfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlinePromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type_group', models.CharField(choices=[('fiction', 'Belletristik (Roman, Kurzgeschichte, Drehbuch)'), ('academic', 'Wissenschaftlich (Paper, Dissertation)'), ('nonfiction', 'Sachtext (Essay, Sachbuch)')], db_index=True, max_length=20)),
                ('template_key', models.CharField(choices=[('enrich_node', 'Einzelnes Kapitel anreichern'), ('detail_pass', 'Detail-Pass (Batch-Generierung)'), ('structure_pass', 'Struktur-Pass (Beat/Akt/Wörter)')], db_index=True, max_length=30)),
                ('system_prompt', models.TextField(help_text='System-Prompt (Rolle, Regeln, Format). Jinja2-Variablen erlaubt.')),
                ('user_prompt_template', models.TextField(help_text='User-Prompt-Template (Jinja2). Verfügbare Variablen: context_block, content_type, beat_phase, act, order, title, target_words, description')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=False, help_text='Nur ein Template pro (group, key) darf aktiv sein.')),
                ('notes', models.TextField(blank=True, default='', help_text='Änderungsnotizen (warum diese Version erstellt wurde).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Outline Prompt-Template',
                'verbose_name_plural': 'Outline Prompt-Templates',
                'db_table': 'wh_outline_prompt_templates',
                'ordering': ['content_type_group', 'template_key', '-version'],
            },
        ),
        migrations.CreateModel(
            name='OutlineQualityRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Unbrauchbar'), (2, 'Schlecht'), (3, 'Akzeptabel'), (4, 'Gut'), (5, 'Ausgezeichnet')])),
                ('feedback', models.TextField(blank=True, default='', help_text='Optionaler Freitext: Was war gut/schlecht?')),
                ('generated_content_snapshot', models.TextField(blank=True, default='', help_text='Snapshot des generierten Inhalts zum Zeitpunkt der Bewertung.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('outline_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_ratings', to='projects.outlinenode')),
                ('prompt_template', models.ForeignKey(blank=True, help_text='Template-Version die diesen Inhalt erzeugt hat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='outlines.outlineprompttemplate')),
            ],
            options={
                'verbose_name': 'Outline Qualitätsbewertung',
                'verbose_name_plural': 'Outline Qualitätsbewertungen',
                'db_table': 'wh_outline_quality_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='outlineprompttemplate',
            constraint=models.UniqueConstraint(fields=('content_type_group', 'template_key', 'version'), name='unique_prompt_version'),
        ),
        migrations.AddConstraint(
            model_name='outlineprompttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('content_type_group', 'template_key'), name='unique_active_prompt'),
        ),
    ]
