# Generated by Django 5.2.12 on 2026-04-01 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_import', '0002_creative_session_book_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativesession',
            name='research_field',
            field=models.CharField(blank=True, help_text='Fachgebiet / Disziplin (nur für wissenschaftliche Sessions)', max_length=200),
        ),
        migrations.AddField(
            model_name='creativesession',
            name='session_type',
            field=models.CharField(choices=[('literary', 'Belletristik'), ('scientific', 'Wissenschaftlich')], default='literary', help_text='Belletristik oder Wissenschaftlich', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookidea',
            name='hook',
            field=models.TextField(blank=True, help_text='Was macht diese Idee besonders/einzigartig?'),
        ),
        migrations.AlterField(
            model_name='bookidea',
            name='logline',
            field=models.TextField(help_text='1-2 Sätze: Wer will was und scheitert woran?'),
        ),
        migrations.AlterField(
            model_name='bookidea',
            name='themes',
            field=models.JSONField(default=list, help_text='Themen als Liste'),
        ),
        migrations.AlterField(
            model_name='creativesession',
            name='inspiration',
            field=models.TextField(blank=True, help_text='Initiale Idee, Genre-Wunsch oder freier Inspirationstext'),
        ),
        migrations.AlterField(
            model_name='creativesession',
            name='premise',
            field=models.TextField(blank=True, help_text='KI-generierte vollständige Premise'),
        ),
        migrations.AlterField(
            model_name='creativesession',
            name='style_dna_hint',
            field=models.TextField(blank=True, help_text='Optionaler Stil-Hinweis für die KI-Generierung'),
        ),
        migrations.AlterField(
            model_name='creativesession',
            name='title',
            field=models.CharField(help_text='Arbeitstitel der Session (z.B. Projektname oder Ideen-Thema)', max_length=200),
        ),
        migrations.AlterField(
            model_name='ideaimportdraft',
            name='committed_sections',
            field=models.JSONField(default=list, help_text='z.B. ["metadata", "outline", "characters"]', verbose_name='Committete Sektionen'),
        ),
        migrations.AlterField(
            model_name='ideaimportdraft',
            name='extracted_data',
            field=models.JSONField(help_text='ExtractedIdea als JSON (Pydantic-Snapshot)', verbose_name='Extrahierte Daten'),
        ),
        migrations.AlterField(
            model_name='ideaimportdraft',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ideaimportdraft',
            name='source_filename',
            field=models.CharField(blank=True, help_text='Originaler Dateiname (leer bei Freitext)', max_length=255, verbose_name='Quelldatei'),
        ),
        migrations.AlterField(
            model_name='ideaimportdraft',
            name='source_format',
            field=models.CharField(blank=True, help_text='txt | md | docx | pdf | freetext', max_length=10, verbose_name='Quellformat'),
        ),
        migrations.AlterField(
            model_name='ideaimportdraft',
            name='source_text',
            field=models.TextField(blank=True, help_text='Normalisierter Quelltext (max. 20.000 Zeichen = Extraktions-Limit)', verbose_name='Normalisierter Quelltext'),
        ),
    ]
