# Generated by Django 5.2.12 on 2026-03-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenrePromiseLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_slug', models.SlugField(unique=True)),
                ('genre_label', models.CharField(max_length=100)),
                ('core_promise', models.TextField(help_text='Was verspricht dieses Genre dem Leser implizit? (1–3 Sätze)', verbose_name='Kern-Versprechen')),
                ('reader_expectation', models.TextField(blank=True, default='', help_text='Was erwartet der Leser konkret? (für LLM-Prompt)', verbose_name='Leser-Erwartung')),
                ('must_haves', models.JSONField(default=list, help_text='["Bedrohung bis 10%", "Clock is ticking", ...]')),
                ('must_not_haves', models.JSONField(default=list, help_text='["Happy End nicht verpflichtend", ...]')),
                ('llm_prompt_block', models.TextField(blank=True, default='', help_text='Fertiger Prompt-Block für Genre-Context-Injection.', verbose_name='LLM-Prompt-Block (Layer 10)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Genre-Versprechen',
                'verbose_name_plural': 'Genre-Versprechen',
                'db_table': 'wh_genre_promise_lookup',
                'ordering': ['sort_order', 'genre_label'],
            },
        ),
        migrations.CreateModel(
            name='TurningPointTypeLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('default_position_percent', models.PositiveSmallIntegerField(default=0, help_text='Typische Position im Roman (0–100%)')),
                ('default_position_normalized', models.DecimalField(blank=True, decimal_places=3, help_text='Normiert (0.0–1.0) — für outlinefw-Kompatibilität', max_digits=4, null=True)),
                ('outlinefw_beat_name', models.CharField(blank=True, default='', help_text='Mapping auf outlinefw BeatDefinition-Name (falls vorhanden)', max_length=80)),
                ('mirrors_type_code', models.SlugField(blank=True, default='', help_text='Code des gespiegelten Typs (z.B. closing_image → opening_image)', max_length=30)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Wendepunkt-Typ',
                'verbose_name_plural': 'Wendepunkt-Typen',
                'db_table': 'wh_turning_point_type_lookup',
                'ordering': ['sort_order'],
            },
        ),
    ]
