# Generated by Django 5.2.12 on 2026-03-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_lookups_drama'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesArcTypeLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Serien-Arc-Typ',
                'verbose_name_plural': 'Serien-Arc-Typen',
                'db_table': 'wh_series_arc_type_lookup',
                'ordering': ['sort_order'],
            },
        ),
    ]
