# Generated by Django 5.2.12 on 2026-03-28 07:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_narrative_role_antagonist'),
        ('worlds', '0003_location_scene_links'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectcharacterlink',
            name='unique_project_character',
        ),
        migrations.RemoveConstraint(
            model_name='projectlocationlink',
            name='unique_project_location',
        ),
        migrations.RemoveConstraint(
            model_name='projectscenelink',
            name='unique_project_scene',
        ),
        migrations.RemoveConstraint(
            model_name='projectworldlink',
            name='unique_project_world',
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='antagonist_logic',
            field=models.TextField(blank=True, default='', help_text='Warum glaubt der Antagonist, das Richtige zu tun?', verbose_name='Antagonisten-Logik'),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='antagonist_type',
            field=models.CharField(blank=True, choices=[('person', 'Person / Gruppe'), ('system', 'System / Institution / Gesellschaft'), ('nature', 'Natur / Umwelt / Schicksal'), ('inner_self', 'Inneres Selbst — die eigene dunkle Seite'), ('combination', 'Kombination mehrerer Typen')], default='', max_length=20, verbose_name='Antagonisten-Typ'),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='false_belief',
            field=models.TextField(blank=True, default='', verbose_name='False Belief'),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='flaw',
            field=models.TextField(blank=True, default='', verbose_name='Flaw (psychologischer Riss)'),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='ghost',
            field=models.TextField(blank=True, default='', verbose_name='Ghost (prägender Moment)'),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='information_advantage',
            field=models.TextField(blank=True, default='', help_text='Nur für externe Antagonisten (person, system, nature).', verbose_name='Informationsvorsprung'),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='mirror_to_protagonist',
            field=models.TextField(blank=True, default='', help_text='Was zeigt diese Figur, was der Protagonist sein KÖNNTE?', verbose_name='Spiegel zum Protagonisten'),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='narrative_role',
            field=models.CharField(choices=[('protagonist', 'Protagonist — Hauptfigur mit Arc'), ('antagonist', 'Antagonist — Gegenkraft mit eigener Logik'), ('deuteragonist', 'Deuteragonist — zweite Hauptfigur (B-Story)'), ('mentor', 'Mentor — gibt Werkzeug/Weisheit'), ('ally', 'Verbündeter — Spiegel und Unterstützung'), ('love_interest', 'Liebesinteresse — verkörpert das Need'), ('trickster', 'Trickster — Humor und Dekonstruktion'), ('herald', 'Herold — bringt den Ruf'), ('shapeshifter', 'Gestaltenwandler — zweifelt Loyalität an'), ('shadow', 'Schatten — was wäre der Protagonist wenn...'), ('threshold_guardian', 'Schwellenwächter — testet Entschlossenheit'), ('supporting', 'Nebenfigur — dramaturgische Funktion')], db_index=True, default='supporting', max_length=30, verbose_name='Narrative Rolle'),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='need',
            field=models.TextField(blank=True, default='', verbose_name='Need (innere Wahrheit)'),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='shared_trait_with_protagonist',
            field=models.TextField(blank=True, default='', verbose_name='Gemeinsamkeit mit Protagonisten'),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='true_belief',
            field=models.TextField(blank=True, default='', verbose_name='True Belief (Erkenntnis am Ende)'),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='want',
            field=models.TextField(blank=True, default='', verbose_name='Want (äußeres Ziel)'),
        ),
        migrations.AlterField(
            model_name='projectcharacterlink',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectworldlink',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='projectcharacterlink',
            unique_together={('project', 'weltenhub_character_id')},
        ),
        migrations.AlterUniqueTogether(
            name='projectlocationlink',
            unique_together={('project', 'weltenhub_location_id')},
        ),
        migrations.AlterUniqueTogether(
            name='projectscenelink',
            unique_together={('project', 'weltenhub_scene_id')},
        ),
        migrations.AlterUniqueTogether(
            name='projectworldlink',
            unique_together={('project', 'weltenhub_world_id')},
        ),
    ]
