# Generated by Django 5.2.6 on 2026-04-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0004_narrative_role_antagonist'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcharacterlink',
            name='character_status',
            field=models.CharField(choices=[('alive', 'Lebt'), ('dead', 'Tot'), ('missing', 'Vermisst'), ('unknown', 'Unbekannt')], default='alive', max_length=20, verbose_name='Status im Plot'),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='first_appearance',
            field=models.CharField(blank=True, default='', help_text='Kapitel oder Szene, in der die Figur erstmals erscheint.', max_length=100, verbose_name='Erster Auftritt'),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='secret_from_whom',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Geheimnis — Vor wem'),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='secret_what',
            field=models.TextField(blank=True, default='', help_text='Was verbirgt die Figur?', verbose_name='Geheimnis — Was'),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='secret_why',
            field=models.TextField(blank=True, default='', verbose_name='Geheimnis — Warum'),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='voice_pattern',
            field=models.TextField(blank=True, default='', help_text='Wie redet die Figur? Kurzsätze, Füllwörter, Dialekt, Schweigen als Mittel.', verbose_name='Stimme / Sprechmuster'),
        ),
    ]
