# Generated by Django 5.2.6 on 2026-04-16 07:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_alter_outlinenode_emotional_arc_to_textfield'),
        ('worlds', '0005_character_voice_secret_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('knows', 'Kennt'), ('friend', 'Freundschaft'), ('love', 'Liebesbeziehung'), ('family', 'Familie / Verwandtschaft'), ('rival', 'Rivalität'), ('enemy', 'Feindschaft'), ('mentor', 'Mentor → Schüler'), ('protects', 'Beschützt'), ('distrusts', 'Misstraut'), ('depends_on', 'Abhängig von'), ('betrayed_by', 'Verraten von'), ('secret_from', 'Verbirgt Geheimnis vor')], max_length=20, verbose_name='Beziehungstyp')),
                ('description', models.TextField(blank=True, default='', help_text='Freitext: Was macht diese Beziehung besonders?', verbose_name='Beschreibung')),
                ('since_chapter', models.CharField(blank=True, default='', help_text='Ab welchem Punkt existiert diese Beziehung?', max_length=100, verbose_name='Seit Kapitel/Szene')),
                ('intensity', models.PositiveSmallIntegerField(default=3, help_text='1=oberflächlich, 5=existenziell', verbose_name='Intensität (1-5)')),
                ('is_public', models.BooleanField(default=True, help_text='Wissen andere Figuren von dieser Beziehung?', verbose_name='Öffentlich bekannt?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='worlds.projectcharacterlink', verbose_name='Von')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_relationships', to='projects.bookproject')),
                ('to_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='worlds.projectcharacterlink', verbose_name='Zu')),
            ],
            options={
                'verbose_name': 'Character Relationship',
                'verbose_name_plural': 'Character Relationships',
                'db_table': 'wh_character_relationships',
                'ordering': ['project', '-intensity'],
                'unique_together': {('project', 'from_character', 'to_character', 'relationship_type')},
            },
        ),
    ]
