# Generated by Django 5.2.6 on 2026-04-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0006_character_relationships'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectcharacterlink',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='projectlocationlink',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='backstory',
            field=models.TextField(blank=True, default='', verbose_name='Hintergrundgeschichte (lokal)'),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Beschreibung (lokal)'),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='is_protagonist',
            field=models.BooleanField(default=False, verbose_name='Protagonist'),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Lokaler Cache / Fallback wenn WeltenHub nicht erreichbar', max_length=200, verbose_name='Name (lokal)'),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='personality',
            field=models.TextField(blank=True, default='', verbose_name='Persönlichkeit (lokal)'),
        ),
        migrations.AddField(
            model_name='projectcharacterlink',
            name='source',
            field=models.CharField(blank=True, choices=[('manual', 'Manuell'), ('outline', 'Aus Outline'), ('llm', 'Per LLM generiert'), ('weltenhub', 'WeltenHub')], default='manual', max_length=20, verbose_name='Quelle'),
        ),
        migrations.AddField(
            model_name='projectlocationlink',
            name='atmosphere',
            field=models.TextField(blank=True, default='', verbose_name='Atmosphäre'),
        ),
        migrations.AddField(
            model_name='projectlocationlink',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Beschreibung (lokal)'),
        ),
        migrations.AddField(
            model_name='projectlocationlink',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name (lokal)'),
        ),
        migrations.AddField(
            model_name='projectlocationlink',
            name='significance',
            field=models.TextField(blank=True, default='', verbose_name='Bedeutung für die Geschichte'),
        ),
        migrations.AddField(
            model_name='projectlocationlink',
            name='source',
            field=models.CharField(blank=True, choices=[('manual', 'Manuell'), ('outline', 'Aus Outline'), ('llm', 'Per LLM generiert'), ('weltenhub', 'WeltenHub')], default='manual', max_length=20, verbose_name='Quelle'),
        ),
        migrations.AlterField(
            model_name='projectcharacterlink',
            name='weltenhub_character_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID des Charakters in WeltenHub (leer = nur lokal)', null=True),
        ),
        migrations.AlterField(
            model_name='projectlocationlink',
            name='weltenhub_location_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID des Ortes in WeltenHub (leer = nur lokal)', null=True),
        ),
    ]
