# Generated by Django 5.2.6 on 2026-04-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0007_local_character_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectworldlink',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name (lokal)'),
        ),
        migrations.AlterField(
            model_name='projectworldlink',
            name='weltenhub_world_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID der Welt in WeltenHub (leer = nur lokal)', null=True),
        ),
    ]
