# Generated by Django 5.2.12 on 2026-03-28 14:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0001_initial'),
        ('projects', '0016_text_analysis_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchWriteJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_ids', models.JSONField(help_text='Geordnete Liste von OutlineNode-UUIDs (strings)')),
                ('max_chapters', models.PositiveSmallIntegerField(default=10, help_text='Sicherheits-Limit pro Batch-Job')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('running', 'Läuft'), ('done', 'Fertig'), ('failed', 'Fehlgeschlagen'), ('canceled', 'Abgebrochen')], db_index=True, default='pending', max_length=10)),
                ('current_index', models.PositiveSmallIntegerField(default=0)),
                ('completed_count', models.PositiveSmallIntegerField(default=0)),
                ('failed_count', models.PositiveSmallIntegerField(default=0)),
                ('error_log', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Batch-Write-Job',
                'verbose_name_plural': 'Batch-Write-Jobs',
                'db_table': 'wh_batch_write_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='authoringsession',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Authoring Session', 'verbose_name_plural': 'Authoring Sessions'},
        ),
        migrations.AlterModelOptions(
            name='authorstyledna',
            options={'verbose_name': 'Author Style DNA', 'verbose_name_plural': 'Author Style DNAs'},
        ),
        migrations.AlterModelOptions(
            name='chapterdimensionscore',
            options={'verbose_name': 'Chapter Dimension Score', 'verbose_name_plural': 'Chapter Dimension Scores'},
        ),
        migrations.AlterModelOptions(
            name='chapterqualityscore',
            options={'get_latest_by': 'scored_at', 'ordering': ['-scored_at'], 'verbose_name': 'Chapter Quality Score', 'verbose_name_plural': 'Chapter Quality Scores'},
        ),
        migrations.AlterModelOptions(
            name='chapterwritejob',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chapter Write Job', 'verbose_name_plural': 'Chapter Write Jobs'},
        ),
        migrations.AlterModelOptions(
            name='gatedecisiontype',
            options={'ordering': ['sort_order'], 'verbose_name': 'Gate Decision Type', 'verbose_name_plural': 'Gate Decision Types'},
        ),
        migrations.AlterModelOptions(
            name='projectphaseexecution',
            options={'ordering': ['project', 'phase_key'], 'verbose_name': 'Projekt-Phasen-Ausführung', 'verbose_name_plural': 'Projekt-Phasen-Ausführungen'},
        ),
        migrations.AlterModelOptions(
            name='projectqualityconfig',
            options={'verbose_name': 'Project Quality Config', 'verbose_name_plural': 'Project Quality Configs'},
        ),
        migrations.AlterModelOptions(
            name='qualitydimension',
            options={'ordering': ['sort_order', 'code'], 'verbose_name': 'Quality Dimension', 'verbose_name_plural': 'Quality Dimensions'},
        ),
        migrations.RemoveConstraint(
            model_name='authorstyledna',
            name='unique_author_style_dna',
        ),
        migrations.RemoveConstraint(
            model_name='chapterdimensionscore',
            name='unique_quality_score_dimension',
        ),
        migrations.RemoveConstraint(
            model_name='projectphaseexecution',
            name='unique_project_phase_step',
        ),
        migrations.RenameIndex(
            model_name='chapterwritejob',
            new_name='wh_chapter__chapter_c90809_idx',
            old_name='wh_chapter_write_jobs_ref_status',
        ),
        migrations.AlterField(
            model_name='authoringsession',
            name='context_window',
            field=models.JSONField(default=list, help_text='Letzte N KI-Interaktionen für Kontext-Kontinuität'),
        ),
        migrations.AlterField(
            model_name='authoringsession',
            name='current_node_id',
            field=models.CharField(blank=True, help_text='Aktuell bearbeiteter OutlineNode (UUID)', max_length=100),
        ),
        migrations.AlterField(
            model_name='authoringsession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='authoringsession',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Autor der Session (null = systemgeneriert)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authoring_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authorstyledna',
            name='do_list',
            field=models.JSONField(default=list, help_text='Erlaubte/empfohlene Stilmittel'),
        ),
        migrations.AlterField(
            model_name='authorstyledna',
            name='dont_list',
            field=models.JSONField(default=list, help_text='Verbotene Stilmittel'),
        ),
        migrations.AlterField(
            model_name='authorstyledna',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='authorstyledna',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primäres Profil des Autors'),
        ),
        migrations.AlterField(
            model_name='authorstyledna',
            name='name',
            field=models.CharField(help_text='Name des Stilprofils', max_length=200),
        ),
        migrations.AlterField(
            model_name='authorstyledna',
            name='signature_moves',
            field=models.JSONField(default=list, help_text='Charakteristische Stilmittel (Liste von Strings)'),
        ),
        migrations.AlterField(
            model_name='authorstyledna',
            name='taboo_list',
            field=models.JSONField(default=list, help_text='Tabu-Wörter (niemals verwenden)'),
        ),
        migrations.AlterField(
            model_name='chapterdimensionscore',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chapterqualityscore',
            name='chapter_ref',
            field=models.CharField(db_index=True, help_text='Externe Referenz: bfagent.BookChapters.id (int oder UUID)', max_length=100),
        ),
        migrations.AlterField(
            model_name='chapterqualityscore',
            name='findings',
            field=models.JSONField(blank=True, default=dict, help_text='Strukturierte Findings: {deviations: [], suggestions: []}'),
        ),
        migrations.AlterField(
            model_name='chapterqualityscore',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chapterqualityscore',
            name='overall_score',
            field=models.DecimalField(decimal_places=2, help_text='Gewichteter Durchschnitt aller Dimension-Scores', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='chapterwritejob',
            name='chapter_ref',
            field=models.CharField(db_index=True, help_text='Externe Referenz auf bfagent.BookChapters.id', max_length=100),
        ),
        migrations.AlterField(
            model_name='chapterwritejob',
            name='content',
            field=models.TextField(blank=True, help_text='Generierter Kapiteltext (nach Fertigstellung)'),
        ),
        migrations.AlterField(
            model_name='chapterwritejob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chapterwritejob',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('running', 'Läuft'), ('done', 'Fertig'), ('failed', 'Fehlgeschlagen'), ('canceled', 'Abgebrochen')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='gatedecisiontype',
            name='allows_commit',
            field=models.BooleanField(default=False, help_text='Erlaubt Kapitel-Commit/Lock'),
        ),
        migrations.AlterField(
            model_name='gatedecisiontype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectphaseexecution',
            name='context',
            field=models.JSONField(default=dict, help_text='Phasen-übergreifender Kontext (KI-Ergebnisse, Notizen)'),
        ),
        migrations.AlterField(
            model_name='projectphaseexecution',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectphaseexecution',
            name='phase_key',
            field=models.CharField(db_index=True, help_text="Phase-Identifier (z.B. 'outline', 'characters', 'writing')", max_length=100),
        ),
        migrations.AlterField(
            model_name='projectphaseexecution',
            name='step_key',
            field=models.CharField(blank=True, help_text='Schritt innerhalb der Phase (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectqualityconfig',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qualitydimension',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qualitydimension',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Gewichtung für Overall-Score Berechnung', max_digits=3),
        ),
        migrations.AlterUniqueTogether(
            name='authorstyledna',
            unique_together={('author', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='chapterdimensionscore',
            unique_together={('quality_score', 'dimension')},
        ),
        migrations.AlterUniqueTogether(
            name='projectphaseexecution',
            unique_together={('project', 'phase_key', 'step_key')},
        ),
        migrations.AddField(
            model_name='batchwritejob',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_write_jobs', to='projects.bookproject'),
        ),
        migrations.AddField(
            model_name='batchwritejob',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_write_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
